### ISSUE TITLE
It is not an issue, I just want to ask you a question...

### ISSUE THREAD

**Issue by Subfly** [leodr/simple_design#1]
Hello, I have been watching this library for a few months and this is the one of the most promising UI packages in flutter. All I want to ask is will you ever be create more widgets for this design package or are you discontinuing it?

**Comment by leodr** [comment]
> Hello, I have been watching this library for a few months and this is the one of the most promising UI packages in flutter. All I want to ask is will you ever be create more widgets for this design package or are you discontinuing it?

Thanks for the compliment and sorry for taking so long to respond^^

I will not be work on this library anymore, it was more of a personal project that i published. I like to use a lot of different styles with my apps now and so i can't really develop one library to solve all my needs.
